/**
 * Generates `src/graphics/world-data.ts` from Natural Earth's country polygons.
 *
 *   bun packages/hqtui/scripts/generate-world.ts
 *
 * The source is Natural Earth 1:110m Admin 0 countries, which is public domain
 * <https://www.naturalearthdata.com/about/terms-of-use/>. It is fetched rather
 * than committed: the raw file is 800KB of GeoJSON and this only needs running
 * when the borders change, which is roughly never.
 *
 * The output is committed. Regenerating it should be a no-op unless the
 * tolerance below changes.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson";

/**
 * Douglas-Peucker tolerance, in degrees.
 *
 * A world map across an eighty-column terminal is about 160 Braille pixels
 * wide, so one pixel is a bit over two degrees. At one degree the simplified
 * outline is already finer than anything a terminal can show, and it keeps 171
 * of the 177 countries; the six it drops are island states smaller than a pixel,
 * which could be neither seen nor clicked.
 */
const TOLERANCE = 1.0;

/** A country whose bounding box is smaller than this cannot be drawn or hit. */
const MIN_SPAN = 1.5;

type Point = [number, number];

function perpendicular(p: Point, a: Point, b: Point): number {
  const [px, py] = p;
  const [ax, ay] = a;
  const [bx, by] = b;
  const dx = bx - ax;
  const dy = by - ay;
  if (dx === 0 && dy === 0) return Math.hypot(px - ax, py - ay);
  const t = Math.max(0, Math.min(1, ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)));
  return Math.hypot(px - (ax + t * dx), py - (ay + t * dy));
}

/** Douglas-Peucker, iterative so a long coastline cannot blow the stack. */
function simplify(points: Point[], tolerance: number): Point[] {
  if (points.length < 3) return points;
  const keep = new Array<boolean>(points.length).fill(false);
  keep[0] = true;
  keep[points.length - 1] = true;
  const stack: [number, number][] = [[0, points.length - 1]];
  while (stack.length > 0) {
    const [lo, hi] = stack.pop() as [number, number];
    let worst = 0;
    let at = -1;
    for (let i = lo + 1; i < hi; i++) {
      const d = perpendicular(points[i], points[lo], points[hi]);
      if (d > worst) {
        worst = d;
        at = i;
      }
    }
    if (worst > tolerance && at !== -1) {
      keep[at] = true;
      stack.push([lo, at], [at, hi]);
    }
  }
  return points.filter((_, i) => keep[i]);
}

interface Feature {
  properties: Record<string, unknown>;
  geometry: { type: string; coordinates: number[][][] | number[][][][] };
}

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`${SOURCE} responded ${response.status}`);
const collection = (await response.json()) as { features: Feature[] };

const countries: { name: string; iso: string; rings: Point[][] }[] = [];
for (const feature of collection.features) {
  const props = feature.properties;
  const name = String(props.NAME ?? props.NAME_LONG ?? "");
  const iso = String(props.ISO_A2_EH ?? props.ISO_A2 ?? "");
  if (!name) continue;

  const geometry = feature.geometry;
  const polygons = (geometry.type === "MultiPolygon"
    ? geometry.coordinates
    : [geometry.coordinates]) as number[][][][];

  const rings: Point[][] = [];
  for (const polygon of polygons) {
    // Only the outer ring. A lake inside a country is not a border at this
    // resolution, and carrying the holes doubles the data for nothing.
    const ring = polygon[0].map(([x, y]) => [x, y] as Point);
    const xs = ring.map((p) => p[0]);
    const ys = ring.map((p) => p[1]);
    if (Math.max(...xs) - Math.min(...xs) < MIN_SPAN &&
        Math.max(...ys) - Math.min(...ys) < MIN_SPAN) continue;
    const cut = simplify(ring, TOLERANCE);
    if (cut.length >= 3) {
      rings.push(cut.map(([x, y]) => [Math.round(x * 10) / 10, Math.round(y * 10) / 10] as Point));
    }
  }
  if (rings.length > 0) countries.push({ name, iso, rings });
}

countries.sort((a, b) => a.name.localeCompare(b.name));

const points = countries.reduce((n, c) => n + c.rings.reduce((m, r) => m + r.length, 0), 0);
const body = countries
  .map((c) => {
    const rings = c.rings
      .map((ring) => `[${ring.map(([x, y]) => `${x},${y}`).join(",")}]`)
      .join(",\n    ");
    return `  {\n    name: ${JSON.stringify(c.name)},\n    iso: ${JSON.stringify(c.iso)},\n` +
      `    rings: [\n    ${rings},\n    ],\n  },`;
  })
  .join("\n");

const out = `/**
 * Country outlines, flattened for a terminal.
 *
 * Generated by \`packages/hqtui/scripts/generate-world.ts\` from Natural Earth's
 * 1:110m Admin 0 countries, which is public domain. Do not edit by hand.
 *
 * Each ring is a flat list of longitude and latitude pairs -- \`[lon, lat,
 * lon, lat, ...]\` rather than an array of pairs, because at ${points} points the
 * nested form costs an object per coordinate for no gain. A country has more
 * than one ring when it is more than one landmass.
 */

export interface CountryOutline {
  name: string;
  /** ISO 3166-1 alpha-2, where Natural Earth has one. */
  iso: string;
  /** Longitude and latitude, interleaved. */
  rings: number[][];
}

/** ${countries.length} countries, ${points} points, simplified at ${TOLERANCE} degrees. */
export const WORLD_COUNTRIES: readonly CountryOutline[] = [
${body}
];
`;

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, "..", "src", "graphics", "world-data.ts");
writeFileSync(target, out);
console.log(`${countries.length} countries, ${points} points -> ${target}`);
