/**
 * Regenerate the built-in icon pack from an OpenIcon set.
 *
 *   node packages/hqtui/scripts/generate-icons.ts [openicon.json | URL]
 *
 * Defaults to the reference set, github.com/profullstack/openicon. Writes the
 * same table for the TypeScript library and the Go, Python and Rust ports, so
 * `icon("mail")` is the same glyph in every language. Only the terminal
 * glyphs are kept (Nerd Font, Unicode, ASCII) plus aliases; the SVGs are for
 * other surfaces and never ship in a terminal library.
 */

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const DEFAULT = "https://raw.githubusercontent.com/profullstack/openicon/main/openicon.json";
const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");

interface Entry {
  key: string;
  aliases?: string[];
  tui: { nerd?: string; unicode: string; ascii: string };
}
interface Set {
  openicon: string;
  name: string;
  version: string;
  icons: Entry[];
}

/** Byte order, not locale order: the Rust port binary-searches these tables. */
const byteOrder = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);

const source = process.argv[2] ?? DEFAULT;
const set: Set = source.startsWith("http")
  ? await (await fetch(source)).json()
  : JSON.parse(readFileSync(source, "utf8"));

const rows = set.icons
  .map((i) => [i.key, i.tui.nerd ?? "", i.tui.unicode, i.tui.ascii] as const)
  .sort((a, b) => byteOrder(a[0], b[0]));
const aliases = set.icons
  .flatMap((i) => (i.aliases ?? []).map((a) => [a, i.key] as const))
  .sort((a, b) => byteOrder(a[0], b[0]));
const stamp = `${set.name} ${set.version} (OpenIcon ${set.openicon}), ${rows.length} icons`;

/** A string literal every one of the four languages reads the same way. */
const lit = (s: string) =>
  `"${[...s]
    .map((ch) => {
      const cp = ch.codePointAt(0)!;
      if (ch === '"' || ch === "\\") return `\\${ch}`;
      return cp >= 0x20 && cp < 0x7f ? ch : null;
    })
    .map((out, i) => out ?? escapeFor([...s][i]!))
    .join("")}"`;
let escapeFor = (ch: string) => `\\u{${ch.codePointAt(0)!.toString(16)}}`;

function write(rel: string, text: string) {
  writeFileSync(join(root, rel), text);
  console.log(`wrote ${rel}`);
}

// TypeScript: \u{...} escapes.
escapeFor = (ch) => `\\u{${ch.codePointAt(0)!.toString(16)}}`;
write(
  "packages/hqtui/src/icons-data.ts",
  `// Generated by scripts/generate-icons.ts from ${stamp}. Do not edit.
// [key, nerd, unicode, ascii]; an empty nerd means Nerd Fonts has no glyph for it.

export const OPENICON_VERSION = ${lit(set.version)};

export const OPENICON_GLYPHS: ReadonlyArray<readonly [string, string, string, string]> = [
${rows.map((r) => `  [${r.map(lit).join(", ")}],`).join("\n")}
];

export const OPENICON_ALIASES: ReadonlyArray<readonly [string, string]> = [
${aliases.map((a) => `  [${a.map(lit).join(", ")}],`).join("\n")}
];
`,
);

// Go: \U00XXXXXX escapes.
escapeFor = (ch) => `\\U${ch.codePointAt(0)!.toString(16).padStart(8, "0")}`;
write(
  "ports/go/icons_data.go",
  `// Code generated by packages/hqtui/scripts/generate-icons.ts from ${stamp}. DO NOT EDIT.

package hqtui

// OpenIconVersion is the OpenIcon set the built-in pack was generated from.
const OpenIconVersion = ${lit(set.version)}

// {key, nerd, unicode, ascii}; an empty nerd means Nerd Fonts has no glyph for it.
var openIconGlyphs = [][4]string{
${rows.map((r) => `\t{${r.map(lit).join(", ")}},`).join("\n")}
}

var openIconAliases = map[string]string{
${aliases.map(([a, k]) => `\t${lit(a)}: ${lit(k)},`).join("\n")}
}
`,
);

// gofmt aligns the alias map; run it when Go is installed, so the file is
// already in the shape CI's gofmt check expects.
spawnSync("gofmt", ["-w", join(root, "ports/go/icons_data.go")], { stdio: "ignore" });

// Python: \UXXXXXXXX escapes.
escapeFor = (ch) => `\\U${ch.codePointAt(0)!.toString(16).padStart(8, "0")}`;
write(
  "ports/python/hqtui/icons_data.py",
  `# Generated by packages/hqtui/scripts/generate-icons.ts from ${stamp}. Do not edit.
# (key, nerd, unicode, ascii); an empty nerd means Nerd Fonts has no glyph for it.

OPENICON_VERSION = ${lit(set.version)}

OPENICON_GLYPHS = (
${rows.map((r) => `    (${r.map(lit).join(", ")}),`).join("\n")}
)

OPENICON_ALIASES = {
${aliases.map(([a, k]) => `    ${lit(a)}: ${lit(k)},`).join("\n")}
}
`,
);

// Rust: \u{...} escapes.
escapeFor = (ch) => `\\u{${ch.codePointAt(0)!.toString(16)}}`;
write(
  "ports/rust/src/icons_data.rs",
  `// Generated by packages/hqtui/scripts/generate-icons.ts from ${stamp}. Do not edit.
// (key, nerd, unicode, ascii); an empty nerd means Nerd Fonts has no glyph for it.

/// The OpenIcon set the built-in pack was generated from.
pub const OPENICON_VERSION: &str = ${lit(set.version)};

/// Sorted by key, so lookups can binary-search.
pub static OPENICON_GLYPHS: &[(&str, &str, &str, &str)] = &[
${rows.map((r) => `    (${r.map(lit).join(", ")}),`).join("\n")}
];

/// Sorted by alias.
pub static OPENICON_ALIASES: &[(&str, &str)] = &[
${aliases.map((a) => `    (${a.map(lit).join(", ")}),`).join("\n")}
];
`,
);
