"""Compare native rendering to expectations generated by the real TS screens."""
import json
from pathlib import Path
import unittest
from hqtui.testing import render_to_screen
from hqtui_demo.model import State, THEMES
from hqtui_demo.dashboard import dashboard
from hqtui_demo.telemetry_view import telemetry
from hqtui_demo.showcase import components,graphics,themes,input_screen,stress

class ReferenceParity(unittest.TestCase):
    def test_typescript_cells(self):
        root=Path(__file__).resolve().parents[2]
        cases=json.loads((root/"conformance/fixtures/demo-parity.json").read_text())
        sample=json.loads((root/"rust/demo/src/sample.json").read_text())
        for case in cases:
            with self.subTest(screen=case["screen"],theme=case["theme"],width=case["width"]):
                s=State(sample=sample,source="simulated");s.theme_index=THEMES.index(case["theme"])
                s.screen=case["screen"]
                draw={"dashboard":dashboard,"components":components,"graphics":graphics,"themes":themes,"input":input_screen,"stress":stress}.get(s.screen,telemetry)
                f=render_to_screen(case["width"],case["height"],case["theme"],lambda ui:draw(ui,s))
                for y,expected in enumerate(case["hashes"]):
                    h=2166136261
                    for x in range(case["width"]):
                        c=f.cell(x,y)
                        data=c.char.encode()+b'\0'+int(c.fg).to_bytes(4,"little")+int(c.bg).to_bytes(4,"little")+c.attrs.to_bytes(4,"little")
                        for b in data: h=((h^b)*16777619)&0xffffffff
                    self.assertEqual(h,expected,f'row {y}\nTS: {case["text"].splitlines()[y]}\nPY: {f.line(y)}')
